# Configuration Nixpacks pour forcer Node.js 20
# Résout l'erreur: bits-ui@2.5.0 requires Node >=20, got v18.20.5

[variables]
CI = "true"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
# Force Node.js 20 au lieu de 18 auto-détecté
nixPkgs = ["nodejs_20", "pnpm-9_x", "openssl"]
nixLibs = ["libuuid", "libGL"]
aptPkgs = ["curl", "wget"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
nixpkgsArchive = "ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7"

[phases.install]
dependsOn = ["setup"]
cmds = ["pnpm i --frozen-lockfile"]
cacheDirectories = ["/root/.local/share/pnpm/store/v3"]

[phases.build]
dependsOn = ["install"]
cmds = ["pnpm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
cmd = "node build"